config/routes.rb
Bloccit::Application.routes.draw do
  get 'topics/index'

  get 'topics/new'

  get 'topics/show'

  get 'topics/edit'

  devise_for :users
     resources :users, only: [:update, :show, :index]
    
  resources :topics do
      resources :posts, except: [:index], controller: 'topics/posts'
    end
 
  resources :posts, only: [:index] do
      resources :comments, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]
      post '/up-vote' => 'votes#up_vote', as: :up_vote
      post '/down-vote' => 'votes#down_vote', as: :down_vote
    end
   
  get 'about' => 'welcome#about'

  root to: "welcome#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  belongs_to :user
  belongs_to :topic
  
  default_scope { order('rank DESC') }
   scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
  
 

  mount_uploader :postimage, PostimageUploader
  
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true
    
  def up_votes
    votes.where(value: 1).count
  end
  
  def down_votes
    votes.where(value: -1).count
  end  
  
  def points
    votes.sum(:value)   
  end
    
  def update_rank
    age = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
    new_rank = points + age

    update_attribute(:rank, new_rank)
  end
  
  def create_vote
    user.votes.create(value: 1, post: self)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])

  end

  def destroy
     @topic = Topic.find(params[:topic_id])
     @post = Post.find(params[:id])
     title = @post.title
     authorize @post
 
     if @post.destroy
       flash[:notice] = "\"#{title}\" was deleted successfully."
       redirect_to @topic
     else
       flash[:error] = "There was an error deleting the post."
       render :show
     end
   end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post

    if @post.save
      @post.create_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post

    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

private

def post_params

  params.require(:post).permit(:title, :body, :postimage)

end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
      <div class="media">
		  <%= render partial: 'votes/voter', locals: { post: post } %>
        <div class="media-body">
          <h4 class="media-heading">

            <%= image_tag(post.postimage, size: "40x40") %>

            <%= link_to post.title, topic_post_path(post.topic, post) %>
          </h4>
           <small>
              submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br/>
              <%= post.user.name %><br/>
              <%= post.comments.count %> Comments
    </small>
        </div>
      </div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Popular</h1>
    <p class="lead">Active posts this week</p>
    <%= render @posts %>
    <%= will_paginate @posts %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">

 <div class="col-md-2">
	<%= render partial: 'votes/voter', locals: { post: @post } %>
	<h1><%= @post.title %></h1>
	<%= image_tag(@post.postimage) %>
</div>
  <div class="col-md-6">
    <p><%= @post.body %></p>
  </div>

 

  <div class="col-md-4">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
    <% end %>

       <% if policy(@post).destroy? %>
       <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
     <% end %>
	 
	     <div>
	       <h3><%= pluralize(@post.points, 'point') %></h3>
	       <small>
	         <%= pluralize(@post.up_votes, 'up vote') %>, 
	         <%= pluralize(@post.down_votes, 'down vote') %>
	       </small>
	     </div>
        <%= render partial: 'favorites/favorite', locals: {post: @post} %>
 </div>

  	<h3>Comments:</h3>

		<% @post.comments.each do |c|%>
		
       <%= render(partial: 'comments/comment', locals: {comment: c}) %>
	   
	   <% end %>
 
   
    

 

  <% if user_signed_in?  %>
 	<%= render({partial: 'comments/form', locals: {topic: @topic, post: @post}}) %>
  <% end %>